apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: jackett
version: 3.1.5
upstream_version: 7.0.1
appVersion: "auto"
description: API Support for your favorite torrent trackers.
type: application
deprecated: false
home: https://github.com/truecharts/apps/tree/master/stable/jackett
icon: https://truecharts.org/_static/img/jackett-icon.png
keywords:
  - jackett
  - torrent
  - usenet
sources:
  - https://github.com/truecharts/apps/tree/master/stable/jackett
  - https://github.com/k8s-at-home/charts/tree/master/charts/jackett
  - https://github.com/Jackett/Jackett
  - https://hub.docker.com/r/linuxserver/jackett
dependencies:
  - name: common
    repository: https://truecharts.org/
    version: 3.5.5
    # condition:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
  - name: Ornias1993
    email: kjeld@schouten-lebbing.nl
    url: truecharts.org
# annotations:
