# Default values for Syncthing.

image:
  repository: syncthing/syncthing
  pullPolicy: IfNotPresent
  tag: 1.16

strategy:
  type: Recreate

services:
  main:
    port:
      port: 8384

persistence:
  config:
    enabled: true
    emptyDir: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""
    mountPath: "/var/syncthing/"
